### ISSUE TITLE
Main Menu Archiving

### ISSUE THREAD

**Issue by NonstickAtom785** [Zeda/Grammer2#34] opened 2020-01-03 17:50 UTC
If you have a bunch of programs that are read in Grammer and you scroll down to the last one and unarchive it then scroll all the way up and then all the way down again it crashes the calc. Also when you have that many if you try unarchiving one then it unarchives all of the ones below it.

**Comment by Zeda** [comment] 2020-01-03 18:03
Thanks, I'll look into this. I have an idea of what the problem is.

**Comment by NonstickAtom785** [comment] 2020-01-03 18:12
Okay no problem. I'm pretty sure I found some more issues but I can't remeber the rest. I made an Omnicalc Font Editor based off of you Grammer Font Editor. I had to use some assembly code to do it. It just outputs the system large character using `VPutMap` to coordinates in `HL`. I had to do something with Ans too. Thats another thing...

**Comment by Zeda** [comment] 2020-01-03 18:25
Okay, I think that may have fixed it. I found another bug, too, where it wasn't labeling archive status properly.

**Comment by NonstickAtom785** [comment] 2020-01-03 18:29
Is `PutSC` your own special routine for displaying your custom font characters?

**Comment by Zeda** [comment] 2020-01-03 19:31
Yes, it draws a character in the current font mode :)

**Comment by NonstickAtom785** [comment] 2020-01-06 18:28
Could you add the normal small and large fonts to the font mode?

**Comment by Zeda** [comment] 2020-01-06 20:26
I'm confused; do you mean the OS fonts? If so, I have been considering it, especially since E37 made a fast routine for parsing the small font.

**Comment by NonstickAtom785** [comment] 2020-01-07 15:17
Yah that's what I was referring too. It would save space instead of having to use assembly code to do it.

**Comment by Zeda** [comment] 2020-01-10 03:25
Okay, I've added two new font modes; they use the OS text routines, so there aren't the fancy perks of the Grammer text, but it seems to be working.

`Output(4` will set to the small font, `Output(5` will set to the large font.

**Comment by NonstickAtom785** [comment] 2020-01-10 17:02
How did you make the routines? I was gonna say you could look at the zStart large font routine to see if that is more optimized than the os routines. And did you use E37's small text routine?

**Comment by Zeda** [comment] 2020-01-10 17:40
The difficulty isn't the routine; Grammer can already support the OS fonts. The trouble is that the OS font *data* isn't designed to be accessed by external programs, so you have to use weird tricks to figure out where it is located on the calculator (and it isn't guaranteed to be in the same spot depending on the OS version). For now, I didn't bother with writing the code to locate the font data, instead I just used the OS text routines when using the OS fonts. When I get around to adding the code to locate the font data, then the fonts will be drawn with Grammer's routines, with all the perks that come with it. (If anybody else wants to write it, they are welcome to. It's like 10 lines of code or less using E37's trick.)

**Comment by NonstickAtom785** [comment] 2020-01-13 13:48
I wanna try. _But alas my expertise on assembly is just not up to the challenge..._

**Comment by Zeda** [comment] 2020-01-13 20:15
It took a bit more than 10 lines anyway :| I'm closing this issue as it seems to be resolved and we've strayed off topic :P

**Closed as completed by Zeda** 2020-01-13 20:15 UTC
